name: Deploy Jekyll site

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.4'
          bundler-cache: true
      - run: bundle install
      - run: bundle exec jekyll build
      - uses: actions/upload-pages-artifact@v1
      - uses: actions/deploy-pages@v1
        id: deployment